name: DEPLOY TO AWS S3

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        description: "🌳 Branch name"
        required: true
        default: 'main'
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "README.md"

env:
  bucket_name: "road-assistant.adamkierat.pl"
  aws_region: "eu-west-1"
  
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}
      - name: Deploy static files to s3 bucket
        run: aws s3 sync ./ s3://${{ env.bucket_name }} --delete
